repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.11.0
    hooks:
      - id: commitizen
        language_version: "python3.12"
        stages: ["commit-msg"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      # run the Ruff linter
      - id: ruff
        args: [--fix]
      # run the Ruff formatter
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        entry: backend/.venv/bin/mypy
        exclude: settings.py
        language: python
        language_version: python3.12
        types: ["python"]
        require_serial: true
