services:
    app:
        build: .
        command: "poetry run uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
        volumes:
            - ./:/code/
        ports:
            - 8001:8000
        depends_on:
            - db
        env_file:
            - ".env.docker"
    db:
        image: mongo
        volumes:
            - "mongodb_data:/data/db"
        ports:
            - "27018:27017"

volumes:
    mongodb_data:
